### ISSUE TITLE
Csocket incomplete type

### ISSUE THREAD

**Issue by liorko87** [encryptogroup/OTExtension#36]
Hello,

When I'm trying to compile the code, I'm receiving this error:
`error: invalid application of ‘sizeof’ to incomplete type ‘CSocket`

I'm using `g++` v 8.3.0

**Comment by MartKro** [comment]
Can you provide a more detailed description of the error, please? (For example, the line which the error occurs)

**Comment by liorko87** [comment]
I'm trying to implement Yao's protocol with your OTExtension.
I followed this [example](https://github.com/encryptogroup/OTExtension/blob/master/mains/otmain.cpp).
At each party I have `CSocket` as a member: `unique_ptr<CSocket> m_socket;`.

At the ctor of each party, I init `CSocket` like this :
`m_socket = Listen(ipAddr, port);`

At the dtor I got the error I stated above.

**Comment by MartKro** [comment]
Is it your _own_ code which creates the problem or doesn't the otmain compile? I can't reproduce this with gcc 9.1.0.

If it is your _own_ code I would firstly check if the problem is related to the code; especially check if you included all needed headers since the problem you described seems related to https://stackoverflow.com/questions/20934195/invalid-application-of-sizeof-to-incomplete-type-created-classes.

**Comment by liorko87** [comment]
I managed to compile the otmain. I will look for missing include files.
Thanks
